### ISSUE TITLE
Do a new release for newer versions of macOS

### ISSUE THREAD

**Issue by cooljeanius** [iains/darwin-gcc-5#2]
I have a copy of the binaries installed on my computer left over from my Snow Leopard days that I had been able to bootstrap newer versions of GCC with previously, but now that I am on Big Sur, using them as the bootstrap compiler no longer works, with this error appearing in `config.log`:
```
configure:4465: checking whether the C compiler works
configure:4487: /opt/iains/x86_64-apple-darwin10/darwin-gcc-5-3r0/bin/gcc    conftest.c  >&5
ld: library not found for -lSystem
collect2: error: ld returned 1 exit status
```
I think this is an issue that you fixed in newer versions of upstream GCC, so that'd mean either backporting the patch to your GCC 5 branch, or doing a binary release of a newer GCC version than 5. (I need binaries specifically for bootstrapping Ada)

**Comment by cooljeanius** [comment]
Update: I think this can be closed, as I have a binary toolchain based on gcc7 from you (@iains) that works fine for me now...

**Comment by barracuda156** [comment]
@cooljeanius Works for Ada?

**Comment by cooljeanius** [comment]
> @cooljeanius Works for Ada?

Yeah

**Comment by barracuda156** [comment]
@cooljeanius I guess I missed something. Where to find Iain’s gcc7 with support for Ada?

**Comment by cooljeanius** [comment]
> @cooljeanius I guess I missed something. Where to find Iain’s gcc7 with support for Ada?

I forget how I got it originally, but it currently lives in `/opt/iains/x86_64-apple-darwin19/gcc-7-5-toolchain` on my computer. Would you like me to repackage it and send you a copy?

**Comment by barracuda156** [comment]
@cooljeanius Thank you, but x86 won’t help to get it for `ppc`. (I recall Iain mentioned he planned to make newer binaries, but I am not sure it has been done so far.)
